// === Helpers ===

export function buildTargetTagsPrompt(title: string, compactDescription: string) {
  return `Imagine you are a real Etsy customer trying to find this exact item. Write the phrases you would type into the Etsy search bar to find it. Return valid JSON only. It's important that each phrase must be <= 20 characters. Phrases should be what an average person is most likely to type off the top of their head. Only phrases a non-technical person, who doesn't know how search engines work, would type. Tags should be standalone buyer search phrases, not sentence fragments. Prioritize searchable product keywords: item type, material, style, color, theme, occasion, recipient, and use case. Do not include filler words or partial phrases like if, so, you, can, does, not, appear, may, vary, contact, help. Ignore dimensions, package counts, sizing-chart details, policies, shipping, refunds, guarantees, care instructions, download instructions, file-format specs, personalization steps, color variation disclaimers, URLs, and seller notes unless a detail is clearly something buyers search for, like 5x7 print or 8oz candle. Every returned tag must make sense by itself as a phrase a real Etsy buyer might search. Never output sentence fragments, partial instruction text, support/contact text, shipping/delivery text, email/download/file-delivery text, quantity/spec fragments, or color-variation disclaimers. If a phrase sounds like it came from a sentence instead of an Etsy search box, reject it and choose a product keyword phrase instead. Do not copy random fragments from the description. Only return phrases a buyer would type to find this product. Once you, as an average Etsy user, have to pause and think about the next phrase, it's time to stop. Output: ["phrase 1", "phrase 2"]. Title: ${title}, Description: ${compactDescription || "(none)"}`;
}

export function buildDiscoveryTagsPrompt(keywords: unknown) {
  return `Imagine you are generating Etsy-style metadata tags for discoverability (coverage and variety). Phrases need to be relevant to the item and make sense as a search phrase to find the item. Phrases should try to end with noun that describes the item. If the noun has to be reused, use the shortest item noun. Create product-search tags, not description fragments. Prefer 2-4 word keyword phrases that a customer would reasonably type on Etsy. Use the description only for product attributes like item type, material, color, style, occasion, recipient, theme, and use case. Use dimensions or quantities only when they are common buyer search terms, not manufacturing specs or package details. Do not output grammar/filler phrases, contact/help text, policy/logistics text, care text, file-delivery text, or random sentence fragments. Do not use device compatibility terms unless the item itself is for that device. Before returning, silently self-check every phrase. Remove any phrase that sounds like a sentence fragment, instruction, policy, support/contact text, shipping/download/file text, color-variation disclaimer, dimension/spec fragment, or random prose. Replace it with a product-focused Etsy search phrase using item type, material, style, color, theme, occasion, recipient, or use case. Tags must describe the product a buyer wants to find. Generate at least 13 phrases <= 20 characters each. Return valid JSON only. Use the following object to help generate ${JSON.stringify(
    keywords,
  )}. Avoid reusing words from Used when possible. Title is your highest-priority keyword pool. Description is your secondary keyword pool. Output: ["phrase 1", "phrase 2"]`;
}
